### ISSUE TITLE
Incompatible with Official Python Docker Images: Failed to find libpython

### ISSUE THREAD

**Issue by Robbie-Palmer** [alibaba/pemja#19]
I'm trying to build a docker image to host my app with both Java and Python components
```
FROM python:3.9
RUN apt-get update
RUN apt install default-jre -y
COPY myapp.jar ./
CMD java -classpath myapp.jar foo.Main
```
But I get the error
```
java.lang.RuntimeException: Failed to find libpython
        at pemja.utils.CommonUtils.getPythonLibrary(CommonUtils.java:175)
        at pemja.core.PythonInterpreter$MainInterpreter.initialize(PythonInterpreter.java:358)
        at pemja.core.PythonInterpreter.initialize(PythonInterpreter.java:145)
        at pemja.core.PythonInterpreter.<init>(PythonInterpreter.java:46)
```

This appears to be because the path pattern doesn't match what is in this Python image
PemJa looks for `^libpython.*so$`
```
String libPythonPathPattern;
if (isLinuxOs()) {
    libPythonPathPattern = "^libpython.*so$";
} else if (isMacOs()) {
    libPythonPathPattern = "^libpython.*dylib$";
} else {
    throw new RuntimeException("Unsupported os ");
}
if (libFile.isDirectory()) {
    for (File f : Objects.requireNonNull(libFile.listFiles())) {
        if (f.isFile() && Pattern.matches(libPythonPathPattern, f.getName())) {
            return f.getAbsolutePath();
        }
    }
}
throw new RuntimeException("Failed to find libpython");
```

When the actual contents of `/usr/local/lib` is:
`libpython3.9.so  libpython3.9.so.1.0  libpython3.so  pkgconfig  python3.9`

**Comment by Robbie-Palmer** [comment]
Nevermind, this wasn't to do with PemJa, it's because I created a virtual environment, and venvs don't copy over libpython 😓 
Solved by symlinking libpython to where the venv python executable is looking `RUN ln -s /usr/local/lib/* /usr/lib/; exit 0`
