### ISSUE TITLE
Failed to find the function after exec

### ISSUE THREAD

**Issue by syntomic** [alibaba/pemja#26]
I define a function by exec,  but invoke this function failed, eg:
```java
interpreter.exec("def f(a):return a");
interpreter.invoke("f", 1);
``` 
then throw:
```
Exception in thread "main" pemja.core.PythonException: <class 'RuntimeError'>: Failed to find the function `f` 
        at pemja.core.PythonInterpreter.invokeOneArgInt(Native Method)
        at pemja.core.PythonInterpreter.invokeOneArg(PythonInterpreter.java:184)
        at pemja.core.PythonInterpreter.invoke(PythonInterpreter.java:93)
```

**Comment by HuangXingBo** [comment]
Thanks a lot for the report. I will take a look.

**Comment by HuangXingBo** [comment]
I tried it and didn't encounter this problem. It may have been fixed in some other fix.
