### ISSUE TITLE
mac m1 throw UnsatisfiedLinkError

### ISSUE THREAD

**Issue by tangjx** [alibaba/pemja#5]
mac m1 run demo throw
java.lang.UnsatisfiedLinkError: pemja.core.PythonInterpreter$MainInterpreter.initialize()
debug find  PythonInterpreter.initialize() function "System.load(pemjaLibPath)" throw error, but the pemjaLibPath pemja_core.cpython-39-darwin.so exists. wish help. 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/2392098/170807225-333de90d-7e34-4d0e-87e6-fbbd1d36fdda.png">

**Comment by HuangXingBo** [comment]
Have you solved this problem?

**Comment by Haaroon** [comment]
we still have this issue on the M1 macbooks

**Comment by rachchan** [comment]
We installed pemja on python 3.9 on M1 macbook and it works with conda

**Comment by ldom** [comment]
If it can help, I had the same problem on my setup with Java 17 (Corretto-17). I installed openjdk 11 and it worked with both python 3.9 and 3.10.

**Comment by ldom** [comment]
Also worked with openjdk 17

**Comment by YasuoStudyJava** [comment]
Have you solved this problem? @tangjx   
I met the problem when running pyflink task in Python-3.7.11，both in x86+centos and aarch64+openeuler. Installation of pemja is successful and the two so exist:
/home/python3711/lib/python3.7/site-packages/pemja_core.cpython-37m-x86_64-linux-gnu.so
/home/python3711/lib/python3.7/site-packages/pemja_utils.cpython-37m-x86_64-linux-gnu.so

But when run pytest of pyflink unit test, 
Caused by: java.lang.UnsatisfiedLinkError: pemja.core.PythonInterpreter$MainInterpreter.initialize()V
E                   	at pemja.core.PythonInterpreter$MainInterpreter.initialize(Native Method)
E                   	at pemja.core.PythonInterpreter$MainInterpreter.access$100(PythonInterpreter.java:332)
E                   	at pemja.core.PythonInterpreter$MainInterpreter$1.run(PythonInterpreter.java:400)

**Comment by tangjx** [comment]
> Have you solved this problem? @tangjx I met the problem when running pyflink task in Python-3.7.11，both in x86+centos and aarch64+openeuler. Installation of pemja is successful and the two so exist: /home/python3711/lib/python3.7/site-packages/pemja_core.cpython-37m-x86_64-linux-gnu.so /home/python3711/lib/python3.7/site-packages/pemja_utils.cpython-37m-x86_64-linux-gnu.so
> 
> But when run pytest of pyflink unit test, Caused by: java.lang.UnsatisfiedLinkError: pemja.core.PythonInterpreter$MainInterpreter.initialize()V E at pemja.core.PythonInterpreter$MainInterpreter.initialize(Native Method) E at pemja.core.PythonInterpreter$MainInterpreter.access$100(PythonInterpreter.java:332) E at pemja.core.PythonInterpreter$MainInterpreter$1.run(PythonInterpreter.java:400)

Sorry,  I has not solved this problem, not used pemja in my project

**Comment by andylau-55** [comment]
![image](https://github.com/alibaba/pemja/assets/19925690/a03c4599-ee35-4862-87dc-80acac0ffbac)
看上去是JDK版本的兼容问题，这边Mac M1芯片 设置OpenJDK version 18 后能执行通过。

**Comment by bgeng777** [comment]
I also meet this problem when running flink1.20.2 using pyflink's thread mode with pemja on my M3 chip Mac.
I finally resolve it by replacing my JDK from adoptjdk8 to another [one](https://cfdownload.adobe.com/pub/adobe/coldfusion/java/java8/java8u441/jdk/jdk-8u441-macosx-aarch64.dmg)
